name: Generate Contribution Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # runs daily

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # ⭐ LIGHT MODE (Grey blocks)
      - name: Generate GitHub Contribution Snake (light)
        uses: Platane/snk@v3
        with:
          github_user_name: rrajshree8
          outputs: |
            dist/github-snake-light.svg
          palette: |
            snake=#ff3b8d
            background=#ffffff
            block=#d1d1d1
            block1=#c7c7c7
            block2=#bdbdbd
            block3=#b3b3b3
            block4=#a9a9a9

      # ⭐ DARK MODE (Black blocks)
      - name: Generate GitHub Contribution Snake (dark)
        uses: Platane/snk@v3
        with:
          github_user_name: rrajshree8
          outputs: |
            dist/github-snake-dark.svg
          palette: |
            snake=#8A2BE2
            background=#000000
            block=#000000
            block1=#0a0a0a
            block2=#111111
            block3=#191919
            block4=#222222

      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
